image: docker-registry.true.nl/true-development:latest

variables:
 # Configure mysql environment variables (https://hub.docker.com/r/_/mysql/)
 MYSQL_DATABASE: application
 MYSQL_ROOT_PASSWORD: root

stages:
- build
- test

cache:
  paths:
  - vendor/

build:install-dependencies:
  stage: build
  script:
  - bash ci/prepare_backend.sh > /dev/null
  - bash ci/install_backend.sh > /dev/null

test:coding-standards:
  stage: test
  dependencies:
  - build:install-dependencies
  before_script:
  - bash ci/prepare_backend.sh > /dev/null
  - source ci/setup_ssh_agent.sh
  - bash ci/install_backend.sh  > /dev/null
  script:
  - vendor/bin/phpcs -p --extensions=php --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./config ./src
  allow_failure: true

test:phpcs-fixer-coding-standards:
  stage: test
  dependencies:
  - build:install-dependencies
  before_script:
  - bash ci/prepare_backend.sh > /dev/null
  - source ci/setup_ssh_agent.sh
  - bash ci/install_backend.sh  > /dev/null
  script:
  - ./vendor/bin/php-cs-fixer fix --dry-run --allow-risky=yes

test:backend-tests:
  stage: test
  dependencies:
  - build:install-dependencies
  services:
  - mysql:latest
  - rabbitmq:latest
  before_script:
  - bash ci/prepare_backend.sh > /dev/null
  - source ci/setup_ssh_agent.sh
  - bash ci/install_backend.sh  > /dev/null
  script:
  - vendor/bin/phpunit --coverage-text --colors=never
